language: go

go:
  - "1.17.x"

script:
  - go mod tidy
  - git diff --exit-code --quiet || (echo "Please run 'go mod tidy' to clean up the 'go.mod' and 'go.sum' files."; false)
  - go vet ./...
  - go test ./...
  - curl -sL https://git.io/goreleaser | bash -s check
  - make install-typescript
  - git diff
# Create a release using goreleaser when tests pass and revision is tagged.
deploy:
- provider: script
  skip_cleanup: true
  script: make release
  on:
    tags: true
    go: "1.17.x"
