name: CI and Release

on:
  push:
    branches:
      - "**" # Run on all branches
    tags:
      - "*" # Trigger on new tags
  pull_request:
    branches:
      - "**" # Trigger on PRs to any branch

permissions:
  contents: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run Go Mod Tidy
        run: go mod tidy

      - name: Check for Uncommitted Changes
        run: git diff --exit-code || (echo "Please run 'go mod tidy' to clean up the 'go.mod' and 'go.sum' files. Your go version should match the one used with travis." && exit 1)

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Go Tests
        run: go test ./...

      - name: Check GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: check

  release:
    runs-on: ubuntu-latest
    needs: checks # Ensure the checks job completes successfully before releasing
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install packr
        run: go install github.com/gobuffalo/packr/v2/packr2@latest

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
